Cross.create(greek_class: "Charter Class")
Cross.create(greek_class: "Alpha Class")
Cross.create(greek_class: "Beta Class")
Cross.create(greek_class: "Gamma Class")
Cross.create(greek_class: "Delta Class")
Cross.create(greek_class: "Founder")
Cross.create(greek_class: "Epsilon Class")
Cross.create(greek_class: "Zeta Class")
Cross.create(greek_class: "Eta Class")
Cross.create(greek_class: "Theta Class")
Cross.create(greek_class: "Iota Class", semester: "Spring", year: "2001")
Cross.create(greek_class: "Kappa Class", semester: "Fall", year: "2001")
Cross.create(greek_class: "Lambda Class", semester: "Spring", year: "2002")
Cross.create(greek_class: "Mu Class", semester: "Fall", year: "2003")
Cross.create(greek_class: "Nu Class", semester: "Spring", year: "2004")
Cross.create(greek_class: "Xi Class", semester: "Fall", year: "2004")
Cross.create(greek_class: "Omicron Class", semester: "Fall", year: "2005")
Cross.create(greek_class: "Pi Class", semester: "Spring", year: "2007")
Cross.create(greek_class: "Rho Class", semester: "Fall", year: "2007")
Cross.create(greek_class: "Sigma Class", semester: "Spring", year: "2008")
Cross.create(greek_class: "Tau Class", semester: "Spring", year: "2009")
Cross.create(greek_class: "Upsilon Class", semester: "Fall", year: "2009")
Cross.create(greek_class: "Phi Class", semester: "Spring", year: "2010")
Cross.create(greek_class: "Chi Class", semester: "Fall", year: "2010")
Cross.create(greek_class: "Psi Class", semester: "Spring", year: "2011")
Cross.create(greek_class: "Omega Class", semester: "Fall", year: "2011")
Cross.create(greek_class: "Alpha Alpha Class", semester: "Spring", year: "2012")
Cross.create(greek_class: "Alpha Beta Class", semester: "Fall", year: "2012")
Cross.create(greek_class: "Alpha Gamma Class", semester: "Spring", year: "2013")
Cross.create(greek_class: "Alpha Delta Class")
Cross.create(greek_class: "Alpha Epsilon Class")
Cross.create(greek_class: "Alpha Zeta Class")
Cross.create(greek_class: "Alpha Eta Class")
Cross.create(greek_class: "Alpha Theta Class")
Cross.create(greek_class: "Alpha Iota Class")



Brother.create(scroll_number: "A034", full_name: "Ritchie Fernandez", cross_id: 1)
Brother.create(scroll_number: "001", full_name: "John Caparas", cross_id: 2)
Brother.create(scroll_number: "002", full_name: "Fiel Rino", cross_id: 2)
Brother.create(scroll_number: "003", full_name: "Joseph T. Orais", cross_id: 2)
Brother.create(scroll_number: "004", full_name: "Michael N Garcia", cross_id: 2)
Brother.create(scroll_number: "005", full_name: "Abe A. Blanco", cross_id: 2)
Brother.create(scroll_number: "006", full_name: "Gene Paek", cross_id: 2)
Brother.create(scroll_number: "007", full_name: "Daniyel M. Garcia", cross_id: 2)
Brother.create(scroll_number: "008", full_name: "Grant D. Luke", cross_id: 3)
Brother.create(scroll_number: "009", full_name: "Nicholas A. Voight", cross_id: 3)
Brother.create(scroll_number: "010", full_name: "Gabriel Rayray", cross_id: 3)
Brother.create(scroll_number: "011", full_name: "Rober W. Newstead", cross_id: 3)
Brother.create(scroll_number: "012", full_name: "Kyoo Eek Choe", cross_id: 3)
Brother.create(scroll_number: "013", full_name: "Rick Lau", cross_id: 3)
Brother.create(scroll_number: "014", full_name: "Erick T. Muramoto", cross_id: 3)
Brother.create(scroll_number: "015", full_name: "Manuel Moreno", cross_id: 3)
Brother.create(scroll_number: "016", full_name: "Noli S. Forales", cross_id: 4)
Brother.create(scroll_number: "017", full_name: "Michael Rino", cross_id: 4)
Brother.create(scroll_number: "018", full_name: "Joseph L. Cabrera", cross_id: 4)
Brother.create(scroll_number: "019", full_name: "Stephen J. Miao", cross_id: 4)
Brother.create(scroll_number: "020", full_name: "Lawrence Dabon", cross_id: 4)
Brother.create(scroll_number: "021", full_name: "Stephen Lum", cross_id: 4)
Brother.create(scroll_number: "022", full_name: "Gerard Apolinar", cross_id: 5)
Brother.create(scroll_number: "023", full_name: "Leonard H. Trac", cross_id: 5)
Brother.create(scroll_number: "024", full_name: "Vinay Singh", cross_id: 5)
Brother.create(scroll_number: "025", full_name: "Joel Sinang", cross_id: 5)
Brother.create(scroll_number: "026", full_name: "Jeremiah Reyes", cross_id: 6)
Brother.create(scroll_number: "027", full_name: "Adam Malbrough", cross_id: 6)
Brother.create(scroll_number: "028", full_name: "Francis Zamora", cross_id: 6)
Brother.create(scroll_number: "029", full_name: "Manuel A. Soto", cross_id: 6)
Brother.create(scroll_number: "030", full_name: "Jason Saluta", cross_id: 7)
Brother.create(scroll_number: "031", full_name: "Mark H. Melendres", cross_id: 7)
Brother.create(scroll_number: "032", full_name: "Randy C. Rullamas", cross_id: 7)
Brother.create(scroll_number: "033", full_name: "Michael A. Gameng", cross_id: 7)
Brother.create(scroll_number: "034", full_name: "Hua Hunyh", cross_id: 7)
Brother.create(scroll_number: "035", full_name: "Stanley S.K. Lee", cross_id: 7)
Brother.create(scroll_number: "036", full_name: "Jerwin Nipay Garcia", cross_id: 8)
Brother.create(scroll_number: "037", full_name: "Isaac T. Beneke", cross_id: 8)
Brother.create(scroll_number: "038", full_name: "Enrique Bibat", cross_id: 9)
Brother.create(scroll_number: "039", full_name: "Albert Nguyen", cross_id: 10)
Brother.create(scroll_number: "040", full_name: "Rhener Solis", cross_id: 10)
Brother.create(scroll_number: "041", full_name: "Kevin Hutchison", cross_id: 10)
Brother.create(scroll_number: "042", full_name: "Jonathan A. Pingue", cross_id: 11)
Brother.create(scroll_number: "043", full_name: "Jordan W. Dodge", cross_id: 11)
Brother.create(scroll_number: "044", full_name: "Daniel Maxfield", cross_id: 11)
Brother.create(scroll_number: "045", full_name: "Lawrence Cheung", cross_id: 11)
Brother.create(scroll_number: "046", full_name: "Jason A. Toledo", cross_id: 11)
Brother.create(scroll_number: "047", full_name: "Shaun F. Alonzo", cross_id: 11)
Brother.create(scroll_number: "048", full_name: "Benjamin Gapuz Jr.", cross_id: 12)
Brother.create(scroll_number: "049", full_name: "Jonathan A. Taa", cross_id: 12)
Brother.create(scroll_number: "050", full_name: "Reggi Scoobi Morris II", cross_id: 12)
Brother.create(scroll_number: "051", full_name: "Ricardo Flores Jr.", cross_id: 13)
Brother.create(scroll_number: "052", full_name: "Michael Geslani", cross_id: 13)
Brother.create(scroll_number: "053", full_name: "Kenny Yan", cross_id: 13)
Brother.create(scroll_number: "054", full_name: "Ryan Lam", cross_id: 14)
Brother.create(scroll_number: "055", full_name: "Jason Prestosa", cross_id: 14)
Brother.create(scroll_number: "056", full_name: "Joseph Ignacio", cross_id: 14)
Brother.create(scroll_number: "057", full_name: "Gabriel D. Vasallo", cross_id: 15)
Brother.create(scroll_number: "058", full_name: "Charlz John C. Boado", cross_id: 15)
Brother.create(scroll_number: "059", full_name: "Rae Canlas", cross_id: 16)
Brother.create(scroll_number: "060", full_name: "Jason Manalang", cross_id: 16)
Brother.create(scroll_number: "061", full_name: "Derrick Valdez", cross_id: 17)
Brother.create(scroll_number: "062", full_name: "Carlo Blanco", cross_id: 17)
Brother.create(scroll_number: "063", full_name: "Samoeun Son", cross_id: 17)
Brother.create(scroll_number: "064", full_name: "Keven Nguav", cross_id: 17)
Brother.create(scroll_number: "065", full_name: "Christopher Gonzales", cross_id: 17)
Brother.create(scroll_number: "066", full_name: "Khai Ly", cross_id: 18)
Brother.create(scroll_number: "067", full_name: "Chester Bataclan", cross_id: 19)
Brother.create(scroll_number: "068", full_name: "Salvador Ramirez", cross_id: 19)
Brother.create(scroll_number: "069", full_name: "Christopher Tran", cross_id: 20)
Brother.create(scroll_number: "070", full_name: "Quincy Fong", cross_id: 21)
Brother.create(scroll_number: "071", full_name: "Ron Tolentino", cross_id: 21)
Brother.create(scroll_number: "072", full_name: "Jose De Anda", cross_id: 21)
Brother.create(scroll_number: "073", full_name: "Brandon Behravresh", cross_id: 21)
Brother.create(scroll_number: "074", full_name: "Eric McGuire", cross_id: 22)
Brother.create(scroll_number: "075", full_name: "Rei Coloma", cross_id: 22)
Brother.create(scroll_number: "076", full_name: "Eidref Laxs", cross_id: 23)
Brother.create(scroll_number: "077", full_name: "Nagel Leus", cross_id: 23)
Brother.create(scroll_number: "078", full_name: "Patrick C. Gallano", cross_id: 23)
Brother.create(scroll_number: "079", full_name: "Earl G. Sabal", cross_id: 24)
Brother.create(scroll_number: "080", full_name: "Sidney D. Quitorio", cross_id: 24)
Brother.create(scroll_number: "081", full_name: "Michael Bicomong", cross_id: 24)
Brother.create(scroll_number: "082", full_name: "Louie Aguilar", cross_id: 24)
Brother.create(scroll_number: "083", full_name: "John Nguyen", cross_id: 25)
Brother.create(scroll_number: "084", full_name: "Hansel Fernandes", cross_id: 25)
Brother.create(scroll_number: "085", full_name: "Alan James Barnett", cross_id: 25)
Brother.create(scroll_number: "086", full_name: "Donald Phonseya", cross_id: 25)
Brother.create(scroll_number: "087", full_name: "Davith Kaing", cross_id: 25)
Brother.create(scroll_number: "088", full_name: "Marvin Javier", cross_id: 25)
Brother.create(scroll_number: "089", full_name: "Sang Yeop Lee", cross_id: 25)
Brother.create(scroll_number: "090", full_name: "Clifford Sun", cross_id: 25)
Brother.create(scroll_number: "091", full_name: "Jack Cen", cross_id: 26)
Brother.create(scroll_number: "092", full_name: "Santino Rafanan", cross_id: 26)
Brother.create(scroll_number: "093", full_name: "Andrew Chen", cross_id: 26)
Brother.create(scroll_number: "094", full_name: "Geoffrey Tolentino", cross_id: 26)
Brother.create(scroll_number: "095", full_name: "Kevin McCarthy", cross_id: 26)
Brother.create(scroll_number: "096", full_name: "Ivan Ung", cross_id: 26)
Brother.create(scroll_number: "097", full_name: "Mykal Ross Hall", cross_id: 26)
Brother.create(scroll_number: "098", full_name: "Daniel Ngyuen", cross_id: 26)
Brother.create(scroll_number: "099", full_name: "Rohit Lal", cross_id: 27)
Brother.create(scroll_number: "100", full_name: "Jay Choe", cross_id: 27)
Brother.create(scroll_number: "101", full_name: "Charles Ho", cross_id: 27)
Brother.create(scroll_number: "102", full_name: "Thomas Lin", cross_id: 27)
Brother.create(scroll_number: "103", full_name: "Kenny Laprelle", cross_id: 27)
Brother.create(scroll_number: "104", full_name: "Chris Java", cross_id: 27)
Brother.create(scroll_number: "105", full_name: "Gabriel Stewart", cross_id: 27)
Brother.create(scroll_number: "106", full_name: "Steven Fu", cross_id: 27)
Brother.create(scroll_number: "107", full_name: "Alvin Dan Pangan", cross_id: 27)
Brother.create(scroll_number: "108", full_name: "Matthew Divina", cross_id: 27)
Brother.create(scroll_number: "109", full_name: "Brian Young", cross_id: 27)
Brother.create(scroll_number: "110", full_name: "Mason Yang", cross_id: 27)
Brother.create(scroll_number: "111", full_name: "Henry Van Nguyen", cross_id: 27)
Brother.create(scroll_number: "112", full_name: "Cyrillo James Silvestre", cross_id: 27)
Brother.create(scroll_number: "113", full_name: "Garrett Jee", cross_id: 27)
Brother.create(scroll_number: "114", full_name: "Angelo Dimalanta", cross_id: 27)
Brother.create(scroll_number: "115", full_name: "Jarry Viet Truong", cross_id: 28)
Brother.create(scroll_number: "116", full_name: "Charlie Boado", cross_id: 28)
Brother.create(scroll_number: "117", full_name: "Joshua Lawas", cross_id: 28)
Brother.create(scroll_number: "118", full_name: "Joey Ma", cross_id: 28)
Brother.create(scroll_number: "119", full_name: "Edward Luu", cross_id: 29)
Brother.create(scroll_number: "120", full_name: "Alexander Do", cross_id: 29)
Brother.create(scroll_number: "121", full_name: "Bryan Linda", cross_id: 29)
Brother.create(scroll_number: "122", full_name: "Michael Akwetey", cross_id: 29)
Brother.create(scroll_number: "123", full_name: "Chad Ikeda", cross_id: 30)
Brother.create(scroll_number: "124", full_name: "Johnson Ho", cross_id: 30)
Brother.create(scroll_number: "125", full_name: "Tuong Quach", cross_id: 30)
Brother.create(scroll_number: "126", full_name: "Josh Shen", cross_id: 30)
Brother.create(scroll_number: "127", full_name: "Allen Luong", cross_id: 30)
Brother.create(scroll_number: "128", full_name: "Jimmy Vo", cross_id: 30)
Brother.create(scroll_number: "129", full_name: "Wayne Nguyen", cross_id: 30)
Brother.create(scroll_number: "130", full_name: "Julio Juarez", cross_id: 31)
Brother.create(scroll_number: "131", full_name: "Andrew Carreon", cross_id: 31)
Brother.create(scroll_number: "132", full_name: "Eddie Lee", cross_id: 32)
Brother.create(scroll_number: "133", full_name: "Austin Deleon", cross_id: 32)
Brother.create(scroll_number: "134", full_name: "Kenneth Lee", cross_id: 32)
Brother.create(scroll_number: "135", full_name: "Tommy Lee", cross_id: 32)
Brother.create(scroll_number: "136", full_name: "Christopher Wong", cross_id: 32)
Brother.create(scroll_number: "137", full_name: "Brian Johnson", cross_id: 33)
Brother.create(scroll_number: "138", full_name: "Ethan Morales", cross_id: 33)
Brother.create(scroll_number: "139", full_name: "Charlie Millar", cross_id: 33)
Brother.create(scroll_number: "140", full_name: "Fredy Lopez", cross_id: 33)
Brother.create(scroll_number: "141", full_name: "Nate Ruiz", cross_id: 33)
Brother.create(scroll_number: "142", full_name: "Khalid Salih", cross_id: 33)
Brother.create(scroll_number: "143", full_name: "Jonathan Shek", cross_id: 33)
Brother.create(scroll_number: "144", full_name: "John Tran", cross_id: 33)
Brother.create(scroll_number: "145", full_name: "Juan Vidal", cross_id: 34)
Brother.create(scroll_number: "146", full_name: "Jeremy Lee", cross_id: 34)
Brother.create(scroll_number: "147", full_name: "Juan Ayala", cross_id: 35)
Brother.create(scroll_number: "148", full_name: "Juan Chavez", cross_id: 35)
Brother.create(scroll_number: "149", full_name: "Kenny Lum", cross_id: 35)
Brother.create(scroll_number: "150", full_name: "Clyndel Camposo", cross_id: 35)
Brother.create(scroll_number: "151", full_name: "Anthony Ma", cross_id: 35)
Brother.create(scroll_number: "152", full_name: "Jose Ramos", cross_id: 35)
Brother.create(scroll_number: "153", full_name: "Nathen Samuta", cross_id: 35)


Position.create(name: "Pledge Lord", brother_id: 130)	
Position.create(name: "President", brother_id: 146)	
Position.create(name: "Vice President", brother_id: 150)	
Position.create(name: "Publicity", brother_id: 122)	
Position.create(name: "Fundraiser", brother_id: 153)	
Position.create(name: "Philanthropy", brother_id: 148)	
Position.create(name: "Social Chair", brother_id: 147)	
Position.create(name: "Treasurer", brother_id: 151)		
Position.create(name: "Secretary", brother_id: 80)	
Position.create(name: "Brotherhood", brother_id: 138)	
Position.create(name: "Academics", brother_id: 152)	
Position.create(name: "Liason", brother_id: 140)	
Position.create(name: "Chancellor", brother_id: 133)	
Position.create(name: "Ritual", brother_id: 143)	
Position.create(name: "Web Master", brother_id: 80, email: "earlsabal@gmail.com", picture: "https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAA0gAAAAJDJiMzU3ZjA5LTM5M2EtNDZlZC05NWE2LWZmZGYyYjU1YzM0OA.jpg")

